name: expenses_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  uuid: ^4.3.3
  kommunicate_flutter: ^1.9.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.20.0
  google_sign_in: ^5.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  auto_size_text:
  google_fonts:
  dash_chat_2:
  flutter_gemini:
  webview_flutter:
  image_picker:

  expense_repository:
    path: packages/expense_repository
  youtube_player_iframe: ^5.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
