// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Cs4IerfF1I0Tn8z1WMdf73tTtlQv4sY',
    appId: '1:572194161715:web:9a6de3af4ba57fc64f0f46',
    messagingSenderId: '572194161715',
    projectId: 'expensetracker--1212',
    authDomain: 'expensetracker--1212.firebaseapp.com',
    storageBucket: 'expensetracker--1212.appspot.com',
    measurementId: 'G-N10SZ4QW8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQspJrJB9RixvD5Z_XR3a_CMkFBDHres4',
    appId: '1:572194161715:android:7fe5d840609a69094f0f46',
    messagingSenderId: '572194161715',
    projectId: 'expensetracker--1212',
    storageBucket: 'expensetracker--1212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDosv06Xr_jqRv_1E_7z4-f7BEEVMHcFPM',
    appId: '1:572194161715:ios:e96c9c9d32f5270c4f0f46',
    messagingSenderId: '572194161715',
    projectId: 'expensetracker--1212',
    storageBucket: 'expensetracker--1212.appspot.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDosv06Xr_jqRv_1E_7z4-f7BEEVMHcFPM',
    appId: '1:572194161715:ios:e96c9c9d32f5270c4f0f46',
    messagingSenderId: '572194161715',
    projectId: 'expensetracker--1212',
    storageBucket: 'expensetracker--1212.appspot.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Cs4IerfF1I0Tn8z1WMdf73tTtlQv4sY',
    appId: '1:572194161715:web:34bd8ff82ee1e0eb4f0f46',
    messagingSenderId: '572194161715',
    projectId: 'expensetracker--1212',
    authDomain: 'expensetracker--1212.firebaseapp.com',
    storageBucket: 'expensetracker--1212.appspot.com',
    measurementId: 'G-QS740K78YM',
  );
}
